### ISSUE TITLE
Síntesis

### ISSUE THREAD

**Issue by Lizzetee** [SistemasTecTlaxiaco/actividad-3-sintesis-Lizzetee#2]
[Sintesis(Lizzete).pdf](https://github.com/SistemasTecTlaxiaco/actividad-3-sintesis-Lizzetee/files/9471462/Sintesis.Lizzete.pdf)

**Comment by salathiel1999** [comment]
18%

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
